-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE game_turn_guesses (
    game_id integer NOT NULL REFERENCES game(id),
    turn_num integer NOT NULL,
    guess_num integer NOT NULL,
    row integer NOT NULL,
    col integer NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX game_turn_guesses_game_id_turn_num_guess_num_idx ON game_turn_guesses(game_id int4_ops,turn_num int4_ops,guess_num int4_ops);
CREATE INDEX game_turn_guesses_game_id_idx ON game_turn_guesses(game_id int4_ops);
