-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE game_player (
    game_id integer NOT NULL REFERENCES game(id),
    team text NOT NULL,
    player_type text NOT NULL,
    player_id integer NOT NULL REFERENCES player(id)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX game_player_player_id_game_id_idx ON game_player(player_id int4_ops,game_id int4_ops);
CREATE INDEX game_player_game_id_idx ON game_player(game_id int4_ops);
