-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE game_board_cell (
    game_id integer NOT NULL REFERENCES game(id),
    row integer NOT NULL,
    col integer NOT NULL,
    word text NOT NULL,
    covered text,
    covered_citizen_team text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX game_board_cell_game_id_row_col_idx ON game_board_cell(game_id int4_ops,row int4_ops,col int4_ops);
CREATE INDEX game_board_cell_game_id_idx ON game_board_cell(game_id int4_ops);
