-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE game (
    id SERIAL PRIMARY KEY,
    current_turn_num integer,
    game_type text,
    winning_team text,
    created_by_player_id integer NOT NULL REFERENCES player(id),
    created_on timestamp with time zone NOT NULL DEFAULT now(),
    game_over boolean NOT NULL DEFAULT false
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX game_pkey ON game(id int4_ops);
CREATE INDEX game_created_by_player_id_idx ON game(created_by_player_id int4_ops);
