-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE game_turn (
    game_id integer NOT NULL REFERENCES game(id),
    turn_num integer NOT NULL,
    team text NOT NULL,
    hint_word text,
    hint_num integer
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX game_turn_game_id_turn_num_idx ON game_turn(game_id int4_ops,turn_num int4_ops);
CREATE INDEX game_turn_game_id_idx ON game_turn(game_id int4_ops);
