-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE player (
    id SERIAL PRIMARY KEY,
    name text NOT NULL,
    sub text NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX player_sub_idx ON player(sub text_ops);
