-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE spec_card (
    id SERIAL PRIMARY KEY,
    hash text NOT NULL UNIQUE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX spec_card_pkey ON spec_card(id int4_ops);
CREATE UNIQUE INDEX spec_card_hash_key ON spec_card(hash text_ops);
