-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE team_board_spec (
    game_id integer NOT NULL REFERENCES game(id),
    team text NOT NULL,
    spec_card_id integer NOT NULL,
    spec_card_side text NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX game_team_board_spec_game_id_team_idx ON team_board_spec(game_id int4_ops,team text_ops);
