-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE word_card (
    word text PRIMARY KEY
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX word_card_pkey ON word_card(word text_ops);
